### ISSUE TITLE
logi - dobrze byłoby pamiętać przed wypuszczeniem kodu, o pozbyciu się logów. Czasami mogą się tam wyświetlać rzeczy przydatne złym ludziom :P 

### ISSUE THREAD

**Issue by ajotka** [Bebeto9009/pig_game#1]
https://github.com/Bebeto9009/pig_game/blob/325fdc7a385c4844f0800ee028fffce445a3c399/app.js#L22

**Comment by pawlakadrian** [comment]
+1 zostawiłem w sumie, jakbym jeszcze miał coś poprawiać, ale rzeczywiście finalnie nie ma sensu by to było w konsoli :)
