### ISSUE TITLE
Inicjalizacja zmiennych

### ISSUE THREAD

**Issue by ajotka** [Bebeto9009/pig_game#3]
https://github.com/Bebeto9009/pig_game/blob/325fdc7a385c4844f0800ee028fffce445a3c399/app.js#L12

Zmień inicjalizację zmiennych na to: 

```
var scores = [0,0],
      roundScore = 0,
      activePlayer = 0,
      dice = 0;
```

Czemu? Jak się nauczysz tego sposobu to nie zapomnisz przypisać wartości początkowej. 
Co jeśli zapomnisz? Wtedy zmienna będzie miała wartość prawdopodobnie ze stosu (można powiedzieć, że randomową), przez co magiczne wyniki Ci mogą wyjść - dotyczy to szczególnie niższych języków programowania.

**Comment by pawlakadrian** [comment]
+1 poprawione, dziękuję za uwagę :)
