### ISSUE TITLE
Optymalizacja kodu

### ISSUE THREAD

**Issue by ajotka** [Bebeto9009/pig_game#6]
Ten kod można ładnie zoptymalizować.
Nie wiem czy poniższe działa, bo pisałam w ciemno :P Ale wierzę, że tak:

```
for (var i = 0; i <= 1; i++) {
    document.querySelector('#score-'+ $i ).textContent = scores[$i];
    document.querySelector('#current-' + $i).textContent = currentScore;
    document.querySelector('#name-' + $i).textContent = 'Player ' + $i+1;
    document.querySelector('.player-' + $i + '-panel').classList.remove('winner').remove('active');
}

document.querySelector('.player-0-panel').classList.add('active');
```

https://github.com/Bebeto9009/pig_game/blob/6c57dd85793addd8d28a17ddb12de8909c552f32/app.js#L25

**Comment by pawlakadrian** [comment]
Dziękuję za uwagę, trochę musiałem poprawić kod na poniższy i teraz działa:

for (var i = 0; i <= 1; i++) {
        document.querySelector('#score-'+ i ).textContent = scores[i];
        document.querySelector('#current-' + i).textContent = currentScore;
        document.querySelector('#name-' + i).textContent = 'Player ' + (i+1);
        document.querySelector('.player-' + i + '-panel').classList.remove('winner');
        document.querySelector('.player-' + i + '-panel').classList.remove('active');
    }
    document.querySelector('.player-0-panel').classList.add('active');
